---

- name: extract code
  shell: | 
    tar -zxvf artifact.tar.gz

- name: npm install 
  shell: |
    npm install

# - name: Stop node
#   shell: |
#     pm2 stop default

- name: Restart node
  shell: |
    pm2 start npm -- start